/**
 * @license
 * Copyright ContextJS All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found at https://github.com/contextjs/context/blob/main/LICENSE
 */

import { Language } from "@contextjs/views";

/**
 * Represents the base class for views in the system.
 */
export abstract class ViewBase<T> {
    /**
     * Writes a literal string to the output.
     * @param text The literal text to write.
     * This method appends the text directly to the output without escaping it.
     */
    protected abstract writeLiteral(text: string): void;

    /**
     * Writes a value to the output, escaping it if necessary.
     * @param value The value to write. If null or undefined, nothing is written.
     * This method escapes the value before appending it to the output.
     */
    protected abstract write(value: string | null | undefined): void;

    /**
     * Escapes a string value for safe output.
     * @param value The string to escape.
     * @returns The escaped string.
     * This method ensures that special characters are properly escaped for output.
     */
    protected abstract escape(value: string): string;

    /**
     * Gets the final output as a string.
     * @returns The accumulated output as a string.
     * This method returns the complete output generated by the view.
     */
    protected abstract getOutput(): T;
}

/**
 * Represents a server-side view in the system.
 */
export declare abstract class ServerView extends ViewBase<string> {

    /**
     * Writes a literal string to the output without escaping it.
     * @param text The literal text to write.
     */
    protected override writeLiteral(text: string): void;

    /**
     * Writes a value to the output, escaping it if necessary.
     * @param value The value to write. If null or undefined, nothing is written.
     */
    protected override write(value: string | null | undefined): void;

    /**
     * Escapes a string value for safe output.
     * @param value The string to escape.
     * @returns The escaped string.
     */
    protected override escape(value: string): string;

    /**
     * Gets the final output as a string.
     * @returns The accumulated output as a string.
     */
    protected override getOutput(): string;
}

/**
 * Provides utility methods for working with languages.
 */
export declare class LanguageExtensions {
    /**
     * Converts a string to its corresponding Language enum value.
     * @param value The string representation of the language.
     * @returns The Language enum value or null if the string does not match any known language.
     */
    public static fromString(value: string): Language | null;
}