name: Benchmarks

permissions:
  contents: write
  pull-requests: write

on:
  workflow_run:
    workflows: ["Tests"]
    types: ["completed"]

env:
  NODE_VERSION: "23.x"

jobs:
  run:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Build
      run: npm run build

    - name: Run WebServer Benchmarks
      run: npm run webserver-benchmarks:ci

    - name: Create Benchmarks Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        author: "contextjs-bot <contextjs-bot@users.noreply.github.com>"
        committer: "contextjs-bot <contextjs-bot@users.noreply.github.com>"
        title: "chore: update benchmarks"
        commit-message: "chore: update benchmarks"
        branch: benchmark/${{ github.run_number }}
        body: "Auto-generated benchmarks update."
        add-paths: |
          README.md

    - name: Auto approve
      if: steps.cpr.outputs.pull-request-operation == 'created'
      run: gh pr review --approve "${{ steps.cpr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Enable Auto-Merge in Merge Queue
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        pull-request-number: ${{ github.event.pull_request.number }}
        merge-method: merge