name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  
env:
  NODE_VERSION: "23.x"

jobs:
  run:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Build
      run: npm run build

    - name: Run Tests
      run: npm run test
      env:
        FORCE_COLOR: true

    - name: Run WebServer Benchmarks
      if: github.event_name == 'push'
      run: npm run webserver-benchmarks

    - name: Create Benchmarks Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        title: "chore: update benchmarks"
        commit-message: "chore: update benchmarks"
        branch: benchmark/${{ github.run_number }}
        body: "Auto-generated benchmarks update."
        labels: auto-benchmark
        add-paths: |
          README.md