name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'src/webserver/webserver/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'src/webserver/webserver/README.md'
  
env:
  NODE_VERSION: "24.x"

jobs:
  run:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Build
      run: npm run build

    - name: Run Tests
      run: npm run test
      env:
        FORCE_COLOR: true